language: ruby

cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - rbx-2

sudo: false

env:
  - ESCAPE_UTILS=1
  - ""

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
      env: ESCAPE_UTILS=1
    - rvm: rbx-2
      env: ESCAPE_UTILS=1
